name: Update translation files

on:
  push:
    branches:
      - "main"
    paths:
      - "**.rst"

permissions:
  contents: write
  pull-requests: write

jobs:
  sphinx-intl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - name: Install Python poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
          virtualenvs-path: .venv
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - name: Update translation files
        id: translation-file
        shell: bash
        run: |
          source .venv/bin/activate
          cd docs/ && make intl-ja
          if git status --porcelain | grep -q '^ [MADRC]'; then
            echo "There are files that can be staged with 'git add'."
            echo "update=true" >> $GITHUB_OUTPUT
          else
            echo "No files to stage."
            echo "update=false" >> $GITHUB_OUTPUT
          fi

      - name: Pull Request
        id: new-pull-request
        if: steps.translation-file.outputs.update == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://github-actions:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}
          GITHASH=$(git rev-parse --short HEAD)
          git switch -c update-translation-${GITHASH}
          git add .
          git commit -m "Update translation file"
          git merge --no-edit origin/main
          if git diff origin/main HEAD --quiet; then
            echo "No changes to merge."
            echo "created=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          git push origin update-translation-${GITHASH}
          NEW_PR_URL=$(gh pr create \
            --base main \
            --head update-translation-${GITHASH} \
            --title "[bot] Update translation files" \
            --body ":twisted_rightwards_arrows: Update translation files ($GITHUB_SHA)")
          if echo $NEW_PR_URL | grep -v -q pull; then
            echo "No new Pull Request"
            echo "created=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          NEW_PR=$(echo $NEW_PR_URL | grep pull | sed -E 's/https.*\/pull\/([0-9]*)/\1/g')
          echo "New PR created: $NEW_PR"
          echo "new_pr=$NEW_PR" >> $GITHUB_ENV
          echo "created=true" >> $GITHUB_OUTPUT

      - name: Check existing PR
        if: steps.translation-file.outputs.update == 'true' && steps.new-pull-request.outputs.created == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_PR: ${{ env.new_pr }}
        run: |
          EXISTING_PR=$(gh pr list --search "[bot] Update translation files" --json number --jq '.[0].number')
          if [[ -n "$EXISTING_PR" ]]; then
            echo "Existing PR found: $EXISTING_PR"
            gh pr comment $EXISTING_PR --body "Addressed by #$NEW_PR"
            gh pr close $EXISTING_PR
          else
            echo "No existing PR found."
